#print('Ауууу!')
#print('Ауууу!')
#print('Привет Привет Привет Привет')
'''a = input()
c = input()
b = input()
print(a)
print(b)
print(c)'''
'''a = input()
c = input()
b = input()
print('Билет на “',a,'”, в кинотеатре "',c,'"в',b,'успешно забронирован!')
a = input()
b = input()
c = input()
d = input()
e = input()
print('Имя:',a)
print(b,c,d,sep='.')
print('email:',e,'@gmail.com')'''
a = int(input())
b = int(input())
c = b // a
d = b - (c * a)
print(c)
print(d)